### ISSUE TITLE
voiced_unvoiced always returns 0

### ISSUE THREAD

**Issue by carlini** [shehzeen/waveguard_defense#2]
When running the code, the lpc defense does not work for me: running the code always emits .wav files that are completely silent.

The command I am running is `python Defender/defender_multiple.py --in_dir /tmp/a/ --out_base /tmp/ --defender_type lpc --defender_hp 10`. When I run this I see the input is non-zero (`INput wav -0.8821411 0.92477417`) but the output is completely zero (`LPC min max 0.0 0.0`).

I've traced it down to the fact that the `voiced_unvoiced` function looks like it always returning an array consisting entirely of 0s. This function depends on only two libraries (numpy and scipy.signal) so I don't believe it's a dependency issue.

The input I'm using is the test input [here](https://github.com/carlini/audio_adversarial_examples/blob/master/sample-000000.wav).

If you'd like to unit test this, then I've provided a numpy file [here](https://nicholas.carlini.com/tmp/lpc.npy) so that if you run

```python
from lpc import voiced_unvoiced
print(voiced_unvoiced(np.load("lpc.npy")))
```

then you should get the output `[0 0 0 0 0 . . . 0 0 0]`.

I think that this is an error, but I'm not certain. Am I doing something wrong here? Maybe the inputs should be pre-processed in some way ahead of time? Or the hyperparameters are wrong (I don't think this is the case as I've tried all values in [2..100]).

**Comment by shehzeen** [comment]
I am not able to reproduce your error. When I run your snippet on the npy you uploaded, I get this.

![image](https://user-images.githubusercontent.com/7191931/127228192-be445fd1-616d-4e39-a672-a6205b7d1be0.png)

**Comment by carlini** [comment]
Just to confirm, you're using numpy==1.16.2 and scipy==1.3.2?

**Comment by carlini** [comment]
Okay, I see the issue. Installing DeepSpeech results in pandas being installed, which installed numpy==1.17.3. For some reason the function behaves very differently with this numpy version. If I revert to numpy==1.16.2 then I can correctly run your code.

If I downgrade, then DeepSpeech can't import Pandas correctly, but it looks like I can just comment this out.
